export * from './inst'
export * from './props'
export * from './slots'
export { default as ProInput } from './input'
export { default as ProTextarea } from './textarea'
export { default as ProPassword } from './password'
