export { useProDescriptions } from './composables/useProDescriptions'
export * from './inst'
export { default as ProDescriptions } from './pro-descriptions'
export * from './props'
export * from './slots'
export * from './types'
