export { default as ProDescriptions } from './descriptions'
export type { ProDescriptionsInst } from './inst'
export * from './props'
export * from './slots'
export type { ProDescriptionColumn, ProDescriptionColumns } from './types'
