export { useProDescriptions } from './composables/useProDescriptions'
export { default as ProDescriptions } from './descriptions'
export * from './inst'
export * from './props'
export * from './slots'
export * from './types'
