export enum InternalValueTypeEnum {
  RATE = 'rate',
  INPUT = 'input',
  DIGIT = 'digit',
  SLIDER = 'slider',
  SWITCH = 'switch',
  UPLOAD = 'upload',
  SELECT = 'select',
  MENTION = 'mention',
  CASCADER = 'cascader',
  PASSWORD = 'password',
  TEXTAREA = 'textarea',
  CHECKBOX = 'checkbox',
  TRANSFER = 'transfer',
  TREE_SELECT = 'tree-select',
  RADIO_GROUP = 'radio-group',
  COLOR_PICKER = 'color-picker',
  DYNAMIC_TAGS = 'dynamic-tags',
  AUTO_COMPLETE = 'auto-complete',
  CHECKBOX_GROUP = 'checkbox-group',

  DATE = 'date',
  TIME = 'time',
  DATE_TIME = 'date-time',
  DATE_YEAR = 'date-year',
  DATE_WEEK = 'date-week',
  DATE_MONTH = 'date-month',
  DATE_RANGE = 'date-range',
  DATE_QUARTER = 'date-quarter',
  DATE_TIME_RANGE = 'date-time-range',
  DATE_YEAR_RANGE = 'date-year-range',
  DATE_MONTH_RANGE = 'date-month-range',
  DATE_QUARTER_RANGE = 'date-quarter-range',
}

export type InternalFieldValueType = `${InternalValueTypeEnum}` | ({} & string)
